from pandas import DataFrame

if 'custom' not in globals():
    from mage_ai.data_preparation.decorators import custom
if 'test' not in globals():
    from mage_ai.data_preparation.decorators import test


@custom
def transform_custom(data:DataFrame, *args, **kwargs):

    # Iterate over each row
    for index, row in data.iterrows():

        submission_id = row['SUBMISSION_ID']
        subreddit_id = row['SUBREDDIT_ID']
        submission_title = row['SUBMISSION_TITLE']
        submission_text = row['SUBMISSION_TEXT']
        submission_author = row['SUBMISSION_AUTHOR']
        is_flagged = row['is_flagged']
        image_caption = row['IMAGE_CAPTION']

        # if image_caption:

            #sightengine code
            #if crossed the threshold

            # try:
            #     # Add a comment indicating that the submission is not flagged
            #     comment_body = "The image associated with this submission has been detected as AI-generated by SafeFeed."
            #     comment = submission.reply(comment_body)

            #     # Pin the comment to the top
            #     comment.mod.distinguish(how='yes', sticky=True)
                
            # except RedditAPIException as e:
            #     # Handle any errors that occur during commenting
            #     print(f"An error occurred while adding comment to submission {submission_id}: {e}")

        # Check if the submission is flagged or contains image
        if is_flagged or image_caption:
            

            #fastapi to LLM get response to delete ot not

            # try:
            #     # Delete the submission using PRAW
            #     subreddit = reddit.subreddit(subreddit_id)
            #     submission = subreddit.submission(submission_id)
            #     submission.delete()

            #     # Send a message to the user (author) notifying them of the takedown
            #     message_subject = "Your submission has been taken down"
            #     message_body = f"Dear {submission_author},\n\nYour submission with ID {submission_id} has been removed due to a violation of community guidelines.\n\nThank you for your understanding."
            #     reddit.redditor(submission_author).message(message_subject, message_body)
                                
            # except RedditAPIException as e:
            #     # Handle any errors that occur during deletion or messaging
            #     print(f"An error occurred while deleting submission {submission_id}: {e}")

            #input response from LLM
            data.at[index, 'SENTIMENT_CATEGORY'] = 'Positive' #Need to add sentiment response from LLM through FastAPI
            data.at[index, 'VIOLATION'] = 'Why it has been moderated if moderated' #Response from LLM
            data.at[index, 'DELETED'] = 'false' #if questionable from response make it false
            data.at[index, 'IS_IMAGE_GENERAL'] = 'false' #get it from LLM for all the image values
            data.at[index, 'IS_IMAGE_SENSITIVE'] = 'false'
            data.at[index, 'IS_IMAGE_EXPLICIT'] = 'false'
            data.at[index, 'IS_QUESTIONABLE'] = 'false'
        else:
            data.at[index, 'SENTIMENT_CATEGORY'] = 'Positive' #Need to add sentiment response from LLM through FastAPI
            data.at[index, 'VIOLATION'] = '' #Response from LLM
            data.at[index, 'DELETED'] = 'false' #if questionable from response make it false
            data.at[index, 'IS_IMAGE_GENERAL'] = 'false' #get it from LLM for all the image values
            data.at[index, 'IS_IMAGE_SENSITIVE'] = 'false'
            data.at[index, 'IS_IMAGE_EXPLICIT'] = 'false'
            data.at[index, 'IS_QUESTIONABLE'] = 'false'

        # Access other columns similarly...
    return data

@test
def test_output(output, *args) -> None:
    """
    Template code for testing the output of the block.
    """
    assert output is not None, 'The output is undefined'
